### ISSUE TITLE
Adding child view to club.cred.synth.views.ElevatedView

### ISSUE THREAD

**Issue by ashwath20** [CRED-CLUB/synth-android#10]
Hi ,

I tried to add child view to **ElevatedView** and **PitView**  but getting below error .

```
club.cred.synth.views.ElevatedView cannot be cast to android.view.ViewGroup
    Caused by: java.lang.ClassCastException: club.cred.synth.views.ElevatedView cannot be cast to android.view.ViewGroup****

```
How to add views to Elevated and PitView

**Comment by nikhilpanju** [comment]
`PitView` and `ElevatedView` are not `ViewGroup`s and hence you can't add any view to them. They serve as pure aesthetic views.

You can create your ViewGroup as per your requirement and constrain PitView/ElevatedView to that ViewGroup. Also, do take a look at the sample app as it has some examples.

**Comment by ashwath20** [comment]
Got it . Thank you :)
