### ISSUE TITLE
How to give bottom depth color?

### ISSUE THREAD

**Issue by rahulraghuwanshii** [CRED-CLUB/synth-android#19]
Hello sir/mam,

I am using a synth for one of my projects, but the synth is not looking good in the light mode because the background is white. When I compare then found that in the sample synth app bottom shadow color is also there for pitview so could you please help me how I can change the pitview bottom shadow color?

I can change the top color using the pitColor attribute.

**Comment by rahulraghuwanshii** [comment]
or bottom depth not visible in white pitcolor

**Comment by nikhilpanju-cred** [comment]
You can check the example given under PitView [here](https://github.com/CRED-CLUB/synth-android#pitview)
Try playing around with appearance attributes
```xml
<club.cred.synth.views.PitView
  app:pitViewAppearance="@style/pit_view_appearance"  
  app:neuCornerRadius="14dp"
  ... />
    
<style name="pit_view_appearance">
    <item name="neuLightShadowColor">...</item>
    <item name="neuDarkShadowColor">...</item>
    <item name="softEdgeColor">...</item>
    <item name="neuCompatColor">...</item>
</style>
```

**Comment by rahulraghuwanshii** [comment]
Thank you.
