### ISSUE TITLE
Shadow in buttons.

### ISSUE THREAD

**Issue by mohitshah3111999** [CRED-CLUB/synth-android#3]
I am using synth in one of my projects.
I have 2 problems while implementing the synth library.
![image](https://user-images.githubusercontent.com/42018918/105958637-e6e91180-60a0-11eb-9e42-75407160e365.png)
1) As you can see in the image above, around the buttons, there is some shadows. How can I remove them?
2) I was trying to remove the black color border around the `cancel` button, but was not able to remove that. How can I remove it?

**Comment by nikhilpanju** [comment]
1. You can't only remove the shadows. Synth is mainly for neumorphic components which have shadows. You can set `android:clipChildren="false"` to the parent of the buttons so that the shadows don't get clipped.
2. You have to set `neuBaseColor` so that the platform color is also changed

**Comment by mohitshah3111999** [comment]
Okay, Thanks for the help.
