### ISSUE TITLE
Blur Effect

### ISSUE THREAD

**Issue by Akshay-Vtro** [CRED-CLUB/synth-android#8]
I like to make this kind of Button.
![Capture](https://user-images.githubusercontent.com/85216308/124469508-11f63080-ddb8-11eb-95fd-634ed93a8df8.PNG)

But I get the blur effect with  app:neuButtonType="elevated_flat". As you can see below image 
![202998535_791637381542785_719696923984093585_n](https://user-images.githubusercontent.com/85216308/124469676-47028300-ddb8-11eb-9eac-4c7a960e358a.jpg)

Could you please guide me?

**Comment by JyotimoyKashyap** [comment]
I have tried to recreate the button style that you have specified. I may not have been able to achieve the desired look to 100% but I think this should help in getting the idea for customizing the button as per one needs. 

![achieved look](https://user-images.githubusercontent.com/55136058/126432645-19ea4d15-1efa-4881-9a1c-cf683cf04e04.jpg)


Below is the code that I used in the layout.xml file


     <club.cred.synth.views.SynthButton
          android:layout_width="wrap_content"
          android:layout_height="wrap_content"
          app:neuButtonType="elevated_flat"
          app:neuFlatButtonAppearance="@style/button_flat_appearance"
          app:neuPlatformAppearance="@style/button_platform_appearance"
          android:paddingStart="40dp"
          android:paddingEnd="40dp"
          android:paddingTop="20dp"
          android:paddingBottom="20dp"
          android:textSize="15dp"
          android:textStyle="bold"
          android:textColor="@color/white"
          android:text="Proceed to pay"/>


Below is the configuration I used in themes.xml 

    <style name="button_platform_appearance">
        <item name="neuLightShadowColor">#505050</item>
        <item name="neuDarkShadowColor">#0f0d0f</item>
        <item name="neuFillStartColor">#3bcf33</item>
        <item name="neuFillEndColor">#1e8b1c</item>
        <item name="neuFillPressedStartColor">#34A814</item>
        <item name="neuFillPressedEndColor">#34A814</item>
        <item name="neuBorderStartColor">#34A814</item>
        <item name="neuBorderEndColor">#34A814</item>
        <item name="neuBorderPressedStartColor">#34A814</item>
        <item name="neuBorderPressedEndColor">#34A814</item>
    </style>

    <style name="button_flat_appearance">
        <item name="neuButtonStartColor">#40F40E</item>
        <item name="neuButtonEndColor">#3CD611</item>
        <item name="neuButtonBorder1StartColor">#34A814</item>
        <item name="neuButtonBorder1EndColor">#34A814</item>
        <item name="neuButtonBorder2StartColor">#34A814</item>
        <item name="neuButtonBorder2EndColor">#34A814</item>
        <item name="neuButtonPressedDarkShadowColor">#34A814</item>
    </style>


Hope with this you will be able to achieve the desired look.

**Comment by Akshay-Vtro** [comment]
@JyotimoyKashyap  I'm really glad you made the button I wanted .... thank you for your help

**Comment by Akshay-Vtro** [comment]
@JyotimoyKashyap I'm really glad you made the button I wanted .... thank you for your help

**Comment by Akshay-Vtro** [comment]
But it doesn't have that `elevated_soft `click effect
