### ISSUE TITLE
How to use pitview? i want the image inside pit view

### ISSUE THREAD

**Issue by safiyaAkhtar06** [CRED-CLUB/synth-android#9]
i have no idea how to use pitview, how to set it in the background of any view

**Comment by nikhilpanju** [comment]
Hey Safiya, you can take a look at the example here from the sample app:
https://github.com/CRED-CLUB/synth-android/blob/master/sample/src/main/res/layout/fragment_main.xml

You can also use `imageView.background = PitDrawable()` to set it manually from code
